#!/usr/bin/env bash
#
# Small Terraform workspace helper for disposable ElastiCache performance runs.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_DEFAULT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="${MULTIRUN_REPO_ROOT:-$REPO_ROOT_DEFAULT}"
RUNS_DIR="$REPO_ROOT/multirun/runs"
BATCHES_DIR="$REPO_ROOT/multirun/batches"
LOGS_DIR="$REPO_ROOT/multirun/logs"
PLUGIN_CACHE_DIR="$REPO_ROOT/.tf-plugin-cache"
DISCRIMINATOR_ALPHABET="abcdefghijklmnopqrstuvwxyz0123456789"

usage() {
    cat <<'USAGE'
Usage:
  multirun.sh configure <name> [--var key=value ...]
  multirun.sh configure-batch <batch> [--var key=value ...] --run name,k=v[,k=v...]
  multirun.sh apply <name>
  multirun.sh apply-all [batch]
  multirun.sh download <name>
  multirun.sh download-all [batch]
  multirun.sh destroy <name>
  multirun.sh destroy-all [batch]
  multirun.sh summary [batch]
USAGE
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

require_cmd() {
    local cmd
    for cmd in "$@"; do
        command -v "$cmd" >/dev/null 2>&1 || die "required command '$cmd' not found on PATH"
    done
}

ensure_layout() {
    mkdir -p "$RUNS_DIR" "$BATCHES_DIR"
}

validate_run_name() {
    local name="${1:-}"
    [[ -n "$name" ]] || die "run name cannot be empty"
    [[ "$name" != "default" ]] || die "'default' is reserved for the root Terraform workflow"
    [[ "$name" != .* ]] || die "run name '$name' must not start with a dot"
    [[ "$name" != *..* ]] || die "run name '$name' must not contain '..'"
    [[ "$name" != *"/"* && "$name" != *"\\"* ]] || die "run name '$name' must not contain path separators"
    [[ ! "$name" =~ [[:space:]] ]] || die "run name '$name' must not contain whitespace"
}

validate_batch_name() {
    local name="${1:-}"
    [[ -n "$name" ]] || die "batch name cannot be empty"
    [[ "$name" != .* ]] || die "batch name '$name' must not start with a dot"
    [[ "$name" != *..* ]] || die "batch name '$name' must not contain '..'"
    [[ "$name" != *"/"* && "$name" != *"\\"* ]] || die "batch name '$name' must not contain path separators"
    [[ ! "$name" =~ [[:space:]] ]] || die "batch name '$name' must not contain whitespace"
}

run_tfvars_path() {
    printf '%s/%s.tfvars\n' "$RUNS_DIR" "$1"
}

batch_manifest_path() {
    printf '%s/%s.list\n' "$BATCHES_DIR" "$1"
}

require_run_tfvars() {
    local name="$1"
    validate_run_name "$name"
    local path
    path=$(run_tfvars_path "$name")
    [[ -f "$path" ]] || die "run '$name' is not configured; expected $path"
}

remove_run_tfvars() {
    local name="$1"
    local path
    path=$(run_tfvars_path "$name")
    rm -f -- "$path"
}

remove_batch_manifest() {
    local batch="$1"
    local manifest
    manifest=$(batch_manifest_path "$batch")
    rm -f -- "$manifest"
}

declared_variables() {
    sed -nE 's/^[[:space:]]*variable[[:space:]]+"([^"]+)".*/\1/p' "$REPO_ROOT/variables.tf"
}

is_declared_variable() {
    local key="$1"
    declared_variables | grep -Fxq "$key"
}

validate_var_key() {
    local key="$1"
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || die "invalid variable key '$key'"
    is_declared_variable "$key" || die "unknown Terraform variable '$key'"
}

split_kv() {
    local kv="$1"
    [[ "$kv" == *=* ]] || die "expected key=value, got '$kv'"
    printf '%s\n%s\n' "${kv%%=*}" "${kv#*=}"
}

hcl_escape_string() {
    local value="$1"
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    value=${value//\$\{/\$\$\{}
    value=${value//%\{/%%\{}
    value=${value//$'\n'/\\n}
    value=${value//$'\r'/\\r}
    printf '%s' "$value"
}

write_tfvars_file() {
    local path="$1"
    shift
    local kv key value
    {
        echo "# Generated by multirun/multirun.sh. Edit manually only for structured values."
        for kv in "$@"; do
            key="${kv%%=*}"
            value="${kv#*=}"
            printf '%s = "%s"\n' "$key" "$(hcl_escape_string "$value")"
        done
    } >"$path"
}

scalar_tfvars_value() {
    local key="$1"
    local file="$REPO_ROOT/terraform.tfvars"
    [[ -f "$file" ]] || return 1
    local matches
    matches=$(sed -nE "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\"([^\"\\\\]*)\"[[:space:]]*(#.*)?$/\1/p" "$file")
    [[ "$(printf '%s\n' "$matches" | sed '/^$/d' | wc -l | tr -d ' ')" == "1" ]] || return 1
    printf '%s\n' "$matches" | sed '/^$/d'
}

value_for_key() {
    local key="$1"
    shift
    local kv
    for kv in "$@"; do
        if [[ "${kv%%=*}" == "$key" ]]; then
            printf '%s\n' "${kv#*=}"
            return 0
        fi
    done
    return 1
}

budget_inputs() {
    local project_name engine_type
    project_name=$(value_for_key project_name "$@" || scalar_tfvars_value project_name || true)
    engine_type=$(value_for_key engine_type "$@" || scalar_tfvars_value engine_type || true)
    if [[ -z "$project_name" ]]; then
        echo "ERROR: cannot infer project_name from terraform.tfvars; pass --var project_name=..." >&2
        return 1
    fi
    if [[ -z "$engine_type" ]]; then
        echo "ERROR: cannot infer engine_type from terraform.tfvars; pass --var engine_type=..." >&2
        return 1
    fi
    printf '%s\n%s\n' "$project_name" "$engine_type"
}

discriminator_budget() {
    local project_name="$1" engine_type="$2"
    printf '%s\n' $((40 - ${#project_name} - ${#engine_type} - 8 - 3))
}

collect_existing_discriminators() {
    local file
    for file in "$RUNS_DIR"/*.tfvars; do
        [[ -f "$file" ]] || continue
        sed -nE 's/^[[:space:]]*run_id_discriminator[[:space:]]*=[[:space:]]*"([^"]*)".*/\1/p' "$file"
    done
}

contains_line() {
    local needle="$1"
    grep -Fxq "$needle"
}

generate_discriminator() {
    local used="$1"
    local a b candidate
    for ((i = 0; i < ${#DISCRIMINATOR_ALPHABET}; i++)); do
        a="${DISCRIMINATOR_ALPHABET:i:1}"
        for ((j = 0; j < ${#DISCRIMINATOR_ALPHABET}; j++)); do
            b="${DISCRIMINATOR_ALPHABET:j:1}"
            candidate="${a}${b}"
            if ! contains_line "$candidate" <<<"$used"; then
                printf '%s\n' "$candidate"
                return 0
            fi
        done
    done
    return 1
}

prepare_run_specs() {
    local spec_count="$1"
    shift
    local -a specs=("$@")
    local used
    used=$(collect_existing_discriminators | sed '/^$/d' || true)
    local prepared="" idx name kv key project_name engine_type budget disc existing
    for ((idx = 0; idx < spec_count; idx++)); do
        name="${specs[idx]%%|*}"
        kv="${specs[idx]#*|}"
        local budget_data
        budget_data=$(budget_inputs $kv) || exit 1
        project_name="${budget_data%%$'\n'*}"
        engine_type="${budget_data#*$'\n'}"
        budget=$(discriminator_budget "$project_name" "$engine_type")
        (( budget >= 2 )) || die "run '$name' has only $budget discriminator characters of cluster_id budget; shorten project_name or engine_type"

        disc=$(value_for_key run_id_discriminator $kv || true)
        if [[ -n "$disc" ]]; then
            [[ "$disc" =~ ^[a-z0-9]{1,8}$ ]] || die "run '$name' has invalid run_id_discriminator '$disc'"
            (( ${#disc} <= budget )) || die "run '$name' discriminator '$disc' exceeds $budget-character budget"
        else
            disc=$(generate_discriminator "$used") || die "two-character discriminator sequence exhausted"
            kv="${kv} run_id_discriminator=${disc}"
        fi

        if contains_line "$disc" <<<"$used"; then
            die "duplicate run_id_discriminator '$disc'"
        fi
        used="${used}"$'\n'"${disc}"
        prepared="${prepared}${name}|${kv}"$'\n'
    done
    printf '%s' "$prepared"
}

parse_vars() {
    local -n out_ref=$1
    shift
    local kv key
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --var)
                [[ $# -ge 2 ]] || die "--var requires key=value"
                kv="$2"
                key="${kv%%=*}"
                [[ "$kv" == *=* ]] || die "--var requires key=value"
                validate_var_key "$key"
                out_ref+=("$kv")
                shift 2
                ;;
            *)
                die "unknown option '$1'"
                ;;
        esac
    done
}

cmd_configure() {
    [[ $# -ge 1 ]] || die "configure requires a run name"
    ensure_layout
    local name="$1"
    shift
    validate_run_name "$name"
    local path
    path=$(run_tfvars_path "$name")
    [[ ! -e "$path" ]] || die "$path already exists"
    local -a vars=()
    parse_vars vars "$@"
    local prepared
    prepared=$(prepare_run_specs 1 "${name}|${vars[*]}")
    write_tfvars_file "$path" ${prepared#*|}
    echo "configured $name -> $path"
}

parse_batch_run() {
    local raw="$1"
    [[ "$raw" != *"{"* && "$raw" != *"}"* && "$raw" != *"["* && "$raw" != *"]"* ]] || die "batch --run does not accept embedded JSON; edit the tfvars file manually for structured values"
    IFS=',' read -r -a parts <<<"$raw"
    [[ ${#parts[@]} -ge 1 && -n "${parts[0]}" ]] || die "bad --run '$raw'"
    local name="${parts[0]}"
    validate_run_name "$name"
    local -a kvs=()
    local part key
    for part in "${parts[@]:1}"; do
        [[ "$part" == *=* ]] || die "bad --run '$raw'; expected name,k=v[,k=v...]"
        key="${part%%=*}"
        validate_var_key "$key"
        kvs+=("$part")
    done
    printf '%s|%s\n' "$name" "${kvs[*]}"
}

cmd_configure_batch() {
    [[ $# -ge 1 ]] || die "configure-batch requires a batch name"
    ensure_layout
    local batch="$1"
    shift
    validate_batch_name "$batch"
    local manifest
    manifest=$(batch_manifest_path "$batch")
    [[ ! -e "$manifest" ]] || die "$manifest already exists"
    local -a batch_vars=()
    local -a raw_runs=()
    local kv key
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --var)
                [[ $# -ge 2 ]] || die "--var requires key=value"
                kv="$2"
                [[ "$kv" == *=* ]] || die "--var requires key=value"
                key="${kv%%=*}"
                validate_var_key "$key"
                batch_vars+=("$kv")
                shift 2
                ;;
            --run)
                [[ $# -ge 2 ]] || die "--run requires a run spec"
                raw_runs+=("$2")
                shift 2
                ;;
            *)
                die "unknown option '$1'"
                ;;
        esac
    done
    [[ ${#raw_runs[@]} -gt 0 ]] || die "configure-batch requires at least one --run"

    local -a specs=()
    local parsed name run_kvs merged seen_names=""
    for raw in "${raw_runs[@]}"; do
        parsed=$(parse_batch_run "$raw")
        name="${parsed%%|*}"
        run_kvs="${parsed#*|}"
        if contains_line "$name" <<<"$seen_names"; then
            die "duplicate run name '$name' in batch"
        fi
        seen_names="${seen_names}"$'\n'"${name}"
        [[ ! -e "$(run_tfvars_path "$name")" ]] || die "$(run_tfvars_path "$name") already exists"
        merged="${batch_vars[*]}"
        local rv rk filtered=()
        for rv in $run_kvs; do
            rk="${rv%%=*}"
            filtered=()
            local bv
            for bv in $merged; do
                [[ "${bv%%=*}" == "$rk" ]] || filtered+=("$bv")
            done
            merged="${filtered[*]} ${rv}"
        done
        specs+=("${name}|${merged}")
    done

    local prepared
    prepared=$(prepare_run_specs "${#specs[@]}" "${specs[@]}")
    local line path names=""
    while IFS= read -r line; do
        [[ -n "$line" ]] || continue
        name="${line%%|*}"
        path=$(run_tfvars_path "$name")
        write_tfvars_file "$path" ${line#*|}
        names="${names}${name}"$'\n'
    done <<<"$prepared"
    printf '%s' "$names" >"$manifest"
    echo "configured batch $batch -> $manifest"
}

restore_default_workspace() {
    terraform -chdir="$REPO_ROOT" workspace select default >/dev/null 2>&1 || true
}

select_or_create_workspace() {
    local name="$1"
    if ! terraform -chdir="$REPO_ROOT" workspace select "$name" >/dev/null 2>&1; then
        terraform -chdir="$REPO_ROOT" workspace new "$name" >/dev/null
    fi
    local current
    current=$(terraform -chdir="$REPO_ROOT" workspace show)
    [[ "$current" == "$name" ]] || die "active Terraform workspace is '$current', expected '$name'"
}

select_existing_workspace() {
    local name="$1"
    terraform -chdir="$REPO_ROOT" workspace select "$name" >/dev/null
    local current
    current=$(terraform -chdir="$REPO_ROOT" workspace show)
    [[ "$current" == "$name" ]] || die "active Terraform workspace is '$current', expected '$name'"
}

workspace_exists() {
    local name="$1"
    terraform -chdir="$REPO_ROOT" workspace list 2>/dev/null |
        sed 's/^[*[:space:]]*//' |
        grep -Fxq "$name"
}

state_is_empty() {
    local output
    output=$(terraform -chdir="$REPO_ROOT" state list 2>/dev/null || true)
    [[ -z "$output" ]]
}

run_with_log() {
    local log="$1"
    shift
    mkdir -p "$(dirname "$log")"
    set +e
    "$@" 2>&1 | tee "$log"
    local rc=${PIPESTATUS[0]}
    set -e
    return "$rc"
}

cmd_apply() {
    local name="${1:-}"
    [[ -n "$name" ]] || die "apply requires a run name"
    require_cmd terraform
    require_run_tfvars "$name"
    mkdir -p "$PLUGIN_CACHE_DIR"
    local tfvars="multirun/runs/${name}.tfvars"
    trap restore_default_workspace EXIT
    TF_PLUGIN_CACHE_DIR="$PLUGIN_CACHE_DIR" terraform -chdir="$REPO_ROOT" init -input=false
    select_or_create_workspace "$name"
    if ! state_is_empty; then
        die "workspace '$name' already has Terraform state; destroy first"
    fi
    run_with_log "$LOGS_DIR/$name/apply.log" env TF_PLUGIN_CACHE_DIR="$PLUGIN_CACHE_DIR" \
        terraform -chdir="$REPO_ROOT" apply -input=false -auto-approve "-var-file=$tfvars"
}

json_value() {
    local key="$1"
    jq -r --arg key "$key" '.[$key].value // empty'
}

listing_object_keys() {
    awk 'NF >= 4 {print $4}'
}

listing_has_result_artifacts() {
    grep -E '(^|/)(metrics|logs)/|(^|/)report_status\.json$|(^|/)results_[^/]+\.(html|json)$' >/dev/null
}

s3_source_key_prefix() {
    local source="$1"
    local without_scheme="${source#s3://}"
    local key_prefix="${without_scheme#*/}"
    printf '%s' "$key_prefix"
}

missing_local_files_count() {
    local dest="$1"
    local key_prefix="$2"
    local key rel missing=0
    while IFS= read -r key; do
        [[ -n "$key" ]] || continue
        rel="${key#"$key_prefix"}"
        if [[ "$rel" == "$key" || ! -f "$dest/$rel" ]]; then
            missing=$((missing + 1))
        fi
    done
    printf '%s' "$missing"
}

cmd_download() {
    local name="${1:-}"
    [[ -n "$name" ]] || die "download requires a run name"
    require_cmd terraform jq aws
    require_run_tfvars "$name"
    trap restore_default_workspace EXIT
    select_existing_workspace "$name"
    mkdir -p "$LOGS_DIR/$name"
    local log="$LOGS_DIR/$name/download.log"
    set +e
    {
        local tf_output location run_folder source dest listing_rc object_keys object_count key_prefix missing_count
        tf_output=$(terraform -chdir="$REPO_ROOT" output -json) || exit $?
        location=$(json_value metrics_export_location <<<"$tf_output")
        run_folder=$(json_value run_folder <<<"$tf_output")
        [[ -n "$location" && -n "$run_folder" ]] || die "Terraform outputs must include metrics_export_location and run_folder"
        source="${location}${run_folder}/"
        dest="$REPO_ROOT/results/$run_folder/"
        echo "listing $source"
        set +e
        listing=$(aws s3 ls "$source" --recursive)
        listing_rc=$?
        set -e
        if [[ $listing_rc -ne 0 ]]; then
            echo "ERROR: failed to list $source" >&2
            exit "$listing_rc"
        fi
        if [[ -z "$listing" ]]; then
            echo "no results yet for $name"
            exit 0
        fi
        printf '%s\n' "$listing"
        object_keys=$(listing_object_keys <<<"$listing")
        object_count=$(grep -c . <<<"$object_keys" || true)
        if ! listing_has_result_artifacts <<<"$object_keys"; then
            echo "results not ready for $name: only bootstrap objects are present; not copying partial artifacts"
            exit 0
        fi
        mkdir -p "$dest"
        aws s3 cp "$source" "$dest" --recursive
        key_prefix=$(s3_source_key_prefix "$source")
        missing_count=$(missing_local_files_count "$dest" "$key_prefix" <<<"$object_keys")
        if [[ "$missing_count" -gt 0 ]]; then
            echo "ERROR: downloaded $((object_count - missing_count)) of $object_count listed object(s) for $name" >&2
            exit 1
        fi
        echo "downloaded $object_count listed file(s) for $name"
    } 2>&1 | tee "$log"
    local rc=${PIPESTATUS[0]}
    set -e
    return "$rc"
}

cmd_destroy() {
    local name="${1:-}"
    [[ -n "$name" ]] || die "destroy requires a run name"
    require_cmd terraform
    require_run_tfvars "$name"
    local tfvars="multirun/runs/${name}.tfvars"
    trap restore_default_workspace EXIT
    select_existing_workspace "$name"
    if run_with_log "$LOGS_DIR/$name/destroy.log" terraform -chdir="$REPO_ROOT" destroy -input=false -auto-approve "-var-file=$tfvars"; then
        terraform -chdir="$REPO_ROOT" workspace select default >/dev/null
        terraform -chdir="$REPO_ROOT" workspace delete "$name"
        remove_run_tfvars "$name"
    else
        return $?
    fi
}

runs_for_all() {
    local batch="${1:-}"
    if [[ -n "$batch" ]]; then
        validate_batch_name "$batch"
        local manifest
        manifest=$(batch_manifest_path "$batch")
        [[ -f "$manifest" ]] || die "batch '$batch' does not exist"
        sed '/^[[:space:]]*$/d' "$manifest"
    else
        local file
        for file in "$RUNS_DIR"/*.tfvars; do
            [[ -f "$file" ]] || continue
            basename "$file" .tfvars
        done | sort
    fi
}

cmd_all() {
    local sub="$1"
    shift
    local batch="${1:-}"
    local name rc=0 ok=0 failed=0
    while IFS= read -r name; do
        [[ -n "$name" ]] || continue
        echo "=== $sub $name ==="
        if "cmd_$sub" "$name"; then
            echo "$name: ok"
            ok=$((ok + 1))
        else
            echo "$name: failed" >&2
            failed=$((failed + 1))
            rc=1
        fi
    done < <(runs_for_all "$batch")
    echo "$sub summary: ok=$ok failed=$failed"
    if [[ "$sub" == "destroy" && -n "$batch" && "$failed" -eq 0 ]]; then
        remove_batch_manifest "$batch"
    fi
    return "$rc"
}

cmd_summary() {
    local batch="${1:-}"
    require_cmd terraform
    local initialized=true
    [[ -d "$REPO_ROOT/.terraform" ]] || initialized=false
    local name current
    while IFS= read -r name; do
        [[ -n "$name" ]] || continue
        if ! $initialized; then
            echo "$name: not-initialized"
            continue
        fi
        if workspace_exists "$name"; then
            trap restore_default_workspace EXIT
            select_existing_workspace "$name"
            if state_is_empty; then
                echo "$name: workspace exists, state empty"
            else
                echo "$name: workspace exists, state non-empty"
            fi
        else
            echo "$name: workspace missing"
        fi
    done < <(runs_for_all "$batch")
    if ! $initialized; then
        echo "Terraform is not initialized; run apply for state-backed details."
    fi
}

main() {
    local cmd="${1:-}"
    shift || true
    case "$cmd" in
        configure) cmd_configure "$@" ;;
        configure-batch) cmd_configure_batch "$@" ;;
        apply) cmd_apply "$@" ;;
        apply-all) cmd_all apply "$@" ;;
        download) cmd_download "$@" ;;
        download-all) cmd_all download "$@" ;;
        destroy) cmd_destroy "$@" ;;
        destroy-all) cmd_all destroy "$@" ;;
        summary) cmd_summary "$@" ;;
        ""|-h|--help|help) usage ;;
        *) usage >&2; die "unknown command '$cmd'" ;;
    esac
}

main "$@"
